### ISSUE TITLE
403 Forbidden error when user cancel a payment

### ISSUE THREAD

**Issue by B-Derouet** [pi-apps/pi-platform-docs#67] opened 2021-07-12 19:12 UTC
When we click on the `cancel` button on the payment window, the request to `https://socialchain.app/v2/payments/{payment_id}/cancel` returns a 403 Forbidden error, so we can't cancel a payment and the payment window won't close.

**Comment by vidaniello** [comment] 2021-07-15 20:58
I've just test in production mode with my app and canceling the transaction work well. Try to my app, copy and paste in pi browser this link: donatepi.glitch.me

**Comment by Sten435** [comment] 2021-07-18 09:52
@vidaniello is right the `CANCEL` button does `NOT` work if you're using the `SANDBOX` but when you're in `PRODUCTION` mode the issue is `RESOLVED`.

I tried `CANCELING` the payment with Postman and that works. But in the `SANDBOX ENVIREMENT`, the cancel button does `NOT` work.

**Comment by B-Derouet** [comment] 2021-07-18 10:43
Quite strange, when I test on demo.pi with the Pi Browser application, it works, but with the same application on my computer (in production mode), it doesn't work.

**Comment by hklee93** [comment] 2021-07-27 23:23
Will look into this very soon. Thanks for reporting!

**Comment by hklee93** [comment] 2021-08-11 23:02
I believe this is now fixed. Let me know if it still happens.

**Closed by hklee93** 2021-08-11 23:02 UTC

**Comment by B-Derouet** [comment] 2021-08-12 11:45
Perfect, thank you!
